version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Tacodemanzana1!
    ports:
      - "1433:1433" 

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      - db 
